# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
